server:
  port: 80
  http2:
    enabled: true
  error:
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
  max-http-header-size: 2MB
  shutdown: graceful
spring:
  application:
    name: sibyl
    deskripsi: Application Control and Information Center
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Jakarta
  data:
    mongodb:
      database: "{cipher}d405f733216d006d1b1087e49b843e096ab8a539c140c6b660004ad90ea8e277"
      uri: "{cipher}eae9bbaa31b0867f419d5cc2905fb97ef9f579b1671d2bfa91d612d590d0e67887b94d7d5188b611b3594f9a42ec333e7cf008b821e0800e91b1031f8a69fcd3a8cb41d00703bf6a893e2c54bec36d106b8d3c844fb994802fc16002514cc268231c1a9e874f9ae582ae2e28102af404"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-blessingsoft.herokuapp.com     

  
